cd C:\Users\tata\Downloads\EdgySpoofer\edgey
edgey.exe /SM "System manufacturer"
edgey.exe /SP "System Product Name"
edgey.exe /SV "System Version"
edgey.exe /SS "System Serial Number"
edgey.exe /SU "AUTO"
edgey.exe /SK "SKU"
edgey.exe /SF "To be filled by O.E.M."
edgey.exe /BT "Default string"
edgey.exe /BLC "Default string"
edgey.exe /CM "Default string"
edgey.exe /CV "Default string"
edgey.exe /CS "Default string"
edgey.exe /CA "Default string"
edgey.exe /CSK "Default string"